register(TOOL,
    id = 'convert_person_notes_to_citations',
    name = _("Convert Person Notes to Citations"),
    category = TOOL_UTILS,
    status = STABLE,
    fname = 'ConvertPersonNotesToCitations.py',
    toolclass = 'ConvertPersonNotesToCitations',
    optionclass = 'ConvertPersonNotesToCitationsOptions',
    tool_modes = [TOOL_MODE_CLI],
    authors = ["Dave Schweisguth"],
    authors_email = ["dave@schweisguth.org"],
    description  = _("Convert appropriately structured person notes to citations"),
    version = '0.4',
    gramps_target_version = "5.1",
)
