register(TOOL,
    id = 'convert_of_births_to_residences',
    name = _("Convert 'Of' Births to Residences"),
    category = TOOL_UTILS,
    status = STABLE,
    fname = 'ConvertOfBirthsToResidences.py',
    toolclass = 'ConvertOfBirthsToResidences',
    optionclass = 'ConvertOfBirthsToResidencesOptions',
    tool_modes = [TOOL_MODE_CLI],
    authors = ["Dave Schweisguth"],
    authors_email = ["dave@schweisguth.org"],
    description  = _("Convert birth events in places whose names begin with 'of ' to residence events in those places"),
    version = '0.1',
    gramps_target_version = "5.1",
)
